<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Ionic.BZip2.Tests</RootNamespace>
		<AssemblyName>BZip2Test</AssemblyName>
		<TargetFramework>net48</TargetFramework>
		<ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
		<AssemblyTitle>BZip2Test</AssemblyTitle>
		<Description>test modules for Ionic's BZip2 library</Description>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="Resources\sample1.bz2">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\sample2.bz2">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\dancing-color.ps.bz2">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
		<PackageReference Include="coverlet.collector" Version="6.0.2" />
		<PackageReference Include="Xunit.SkippableFact" Version="1.4.13" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BZip2\BZip2 DLL.csproj" />
		<ProjectReference Include="..\Tools\BZip2\BZip2.csproj" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\TestCommon\Ionic.TestCommon.csproj" />
	</ItemGroup>
	<ItemGroup>
		<!-- assembly-level attributes have to be compiled into each test assembly -->
		<Compile Include="..\TestCommon\TestAssemblyInfo.cs" Link="TestCommon\TestAssemblyInfo.cs" />
	</ItemGroup>
</Project>